### ISSUE TITLE
SSLError: [Errno 1] _ssl.c:510: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by eggeggss** [project-imas/mdm-server#46]
Hi, friends, What is the error mean ? thanks

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/home/eggeggss/mdm_server/server/server.py", line 329, in POST
    queue(cmd, UDID)
  File "/home/eggeggss/mdm_server/server/server.py", line 316, in queue
    wrapper.notify()
  File "build/bdist.linux-i686/egg/APNSWrapper/notifications.py", line 194, in notify
    apnsConnection.connect(apnsHost, self.apnsPort)
  File "build/bdist.linux-i686/egg/APNSWrapper/connection.py", line 215, in connect
    self.context().connect(host, port)
  File "build/bdist.linux-i686/egg/APNSWrapper/connection.py", line 161, in connect
    self.connectionContext.connect((host, port))
  File "/usr/lib/python2.7/ssl.py", line 433, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python2.7/ssl.py", line 423, in _real_connect
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version

**Comment by eggeggss** [comment]
when I upgrade  python2.7.6 to 2.7.9 ,   it is work. protocol version must be  tlsv1_2

**Comment by eggeggss** [comment]
when I upgrade python2.7.6 to 2.7.9 , it is work. protocol version must be tlsv1_2
